name = "ema-saladillo-api"
main = "src/index.js"
compatibility_date = "2026-08-21"

[[d1_databases]]
binding = "DB"
database_name = "ema-saladillo-db"
database_id = "b5b1eef7-5c8d-42a8-a23e-69cd5ae1cd30"
